FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y build-essential procps curl file git && \
    apt-get clean

ENV XDG_RUNTIME_DIR=/var/run/adari
RUN mkdir $XDG_RUNTIME_DIR && chmod 777 $XDG_RUNTIME_DIR

# Create user
RUN useradd -m -d /home/linuxbrew -s /bin/bash linuxbrew
USER linuxbrew

# Install Homebrew
RUN curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
RUN echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/linuxbrew/.bashrc
RUN eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
ENV PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:${PATH}"
ENV LD_LIBRARY_PATH="/home/linuxbrew/.linuxbrew/lib:${LD_LIBRARY_PATH}"

WORKDIR /home/linuxbrew
RUN mkdir .edps EDPS_data

COPY --chown=linuxbrew ./requirements.txt requirements.txt
COPY --chown=linuxbrew ./edps-gui.py edps-gui.py
COPY --chown=linuxbrew ./pdf_handler.py pdf_handler.py
COPY --chown=linuxbrew ./eso-logo.jpg eso-logo.jpg
COPY --chown=linuxbrew ./application.properties .edps/application.properties
COPY --chown=linuxbrew ./logging.yaml .edps/logging.yaml

RUN brew install python@3.11 graphviz
RUN brew tap eso/pipelines
RUN brew install esopipe-fors

RUN pip3.11 install --no-cache-dir --upgrade -r requirements.txt

CMD ["panel", "serve", "edps-gui.py", "--plugins", "pdf_handler", "--address", "0.0.0.0", "--port", "7860",  "--allow-websocket-origin", "*"]
